"""Manga adaptation domain foundation."""

from app.domain.manga.artifacts import (
    AdaptationPlan,
    Beat,
    BeatSheet,
    CharacterDesign,
    CharacterWorldBible,
    EmotionalTone,
    MangaScript,
    MangaScriptScene,
    PanelPurpose,
    ProtagonistContract,
    QualityIssue,
    QualityReport,
    ScriptLine,
    ShotType,
    StoryboardPage,
    StoryboardPanel,
)
from app.domain.manga.continuity import (
    build_continuation_prompt_context,
    should_add_to_be_continued,
    update_ledger_after_slice,
)
from app.domain.manga.facts import merge_fact_registry, normalize_fact_text
from app.domain.manga.types import (
    CharacterContinuityState,
    ContinuityLedger,
    CurrentStoryState,
    FactImportance,
    MangaAssetSpec,
    MangaGenerationOptions,
    MangaPageArtifact,
    MangaPipelineVersion,
    MangaProjectSnapshot,
    MangaSliceSnapshot,
    SliceRole,
    SourceFact,
    SourceRange,
    SourceSlice,
    SourceSliceMode,
    StoryThread,
)

__all__ = [
    "AdaptationPlan",
    "Beat",
    "BeatSheet",
    "CharacterDesign",
    "CharacterContinuityState",
    "CharacterWorldBible",
    "EmotionalTone",
    "ContinuityLedger",
    "CurrentStoryState",
    "FactImportance",
    "MangaAssetSpec",
    "MangaGenerationOptions",
    "MangaPageArtifact",
    "MangaPipelineVersion",
    "MangaScript",
    "MangaScriptScene",
    "MangaProjectSnapshot",
    "MangaSliceSnapshot",
    "PanelPurpose",
    "ProtagonistContract",
    "QualityIssue",
    "QualityReport",
    "ScriptLine",
    "ShotType",
    "SliceRole",
    "SourceFact",
    "SourceRange",
    "SourceSlice",
    "SourceSliceMode",
    "StoryboardPage",
    "StoryboardPanel",
    "StoryThread",
    "build_continuation_prompt_context",
    "should_add_to_be_continued",
    "update_ledger_after_slice",
    "merge_fact_registry",
    "normalize_fact_text",
]
