"""Manga adaptation domain foundation."""

from app.domain.manga.book_understanding import (
    ArcOutline,
    ArcRole,
    ArcSliceEntry,
    BookSynopsis,
    BookUnderstandingBundle,
)
from app.domain.manga.art_direction import (
    CharacterArtDirection,
    CharacterArtDirectionBundle,
    ExpressionDirection,
)
from app.domain.manga.artifacts import (
    AdaptationPlan,
    Beat,
    BeatSheet,
    CharacterAssetPlan,
    CharacterDesign,
    CharacterWorldBible,
    EmotionalTone,
    MangaScript,
    MangaScriptScene,
    PanelPurpose,
    ProtagonistContract,
    QualityIssue,
    QualityReport,
    ScriptLine,
    ShotType,
    SourceFactExtraction,
    StoryboardArtifact,
    StoryboardPage,
    StoryboardPanel,
)
from app.domain.manga.script_review import ScriptIssue, ScriptReviewReport
from app.domain.manga.voice_cards import CharacterVoiceCard, CharacterVoiceCardBundle
from app.domain.manga.page_composition import (
    MAX_CELLS_PER_ROW,
    MAX_ROWS_PER_PAGE,
    PageComposition,
    PageGridRow,
    SliceComposition,
)
from app.domain.manga.render_view import (
    PanelRenderArtifact,
    RenderedPage,
    empty_rendered_page,
)
from app.domain.manga.sprite_quality import (
    AssetSpriteReview,
    MissingExpression,
    SpriteCheck,
    SpriteCheckCode,
    SpriteCheckSeverity,
    SpriteQualityReport,
)
from app.domain.manga.continuity import (
    build_continuation_prompt_context,
    build_recap_seed,
    should_add_to_be_continued,
    update_ledger_after_slice,
)
from app.domain.manga.facts import merge_fact_registry, normalize_fact_text
from app.domain.manga.types import (
    CharacterContinuityState,
    ContinuityLedger,
    CurrentStoryState,
    FactImportance,
    MangaAssetSpec,
    MangaGenerationOptions,
    MangaPageArtifact,
    MangaPipelineVersion,
    MangaProjectSnapshot,
    MangaSliceSnapshot,
    SliceRole,
    SourceFact,
    SourceRange,
    SourceSlice,
    SourceSliceMode,
    StoryThread,
)

__all__ = [
    "AdaptationPlan",
    "ArcOutline",
    "ArcRole",
    "ArcSliceEntry",
    "BookSynopsis",
    "BookUnderstandingBundle",
    "Beat",
    "BeatSheet",
    "AssetSpriteReview",
    "MAX_CELLS_PER_ROW",
    "MAX_ROWS_PER_PAGE",
    "PageComposition",
    "PageGridRow",
    "PanelRenderArtifact",
    "RenderedPage",
    "empty_rendered_page",
    "ScriptIssue",
    "ScriptReviewReport",
    "SliceComposition",
    "SpriteCheck",
    "SpriteCheckCode",
    "SpriteCheckSeverity",
    "SpriteQualityReport",
    "CharacterArtDirection",
    "CharacterArtDirectionBundle",
    "CharacterVoiceCard",
    "CharacterVoiceCardBundle",
    "CharacterAssetPlan",
    "CharacterDesign",
    "CharacterContinuityState",
    "CharacterWorldBible",
    "EmotionalTone",
    "ExpressionDirection",
    "ContinuityLedger",
    "CurrentStoryState",
    "FactImportance",
    "MangaAssetSpec",
    "MangaGenerationOptions",
    "MangaPageArtifact",
    "MangaPipelineVersion",
    "MangaScript",
    "MangaScriptScene",
    "MangaProjectSnapshot",
    "MangaSliceSnapshot",
    "PanelPurpose",
    "ProtagonistContract",
    "QualityIssue",
    "QualityReport",
    "ScriptLine",
    "ShotType",
    "SliceRole",
    "SourceFact",
    "SourceFactExtraction",
    "SourceRange",
    "SourceSlice",
    "SourceSliceMode",
    "StoryboardArtifact",
    "StoryboardPage",
    "StoryboardPanel",
    "StoryThread",
    "build_continuation_prompt_context",
    "build_recap_seed",
    "should_add_to_be_continued",
    "update_ledger_after_slice",
    "merge_fact_registry",
    "normalize_fact_text",
]
